# config.yml

#the Plugin will not go below this amount of slots
minSlots: 10
#the Plugin will not go above this amount of slots
maxSlots: 100
#the Plugin will increase the amount of slots as long as it is below this amount of MSPT
lowerMSPTThreshold: 50.0
#the Plugin will decrease the amount of slots as long as it is above this amount of MSPT
upperMSPTThreshold: 60.0
#the time in seconds between each update
updateInterval: 60
#time in seconds for the rolling average to be calculated over
averageMSPTInterval: 60