name: slotcrafter
version: '${project.version}'
main: org.asdanjer.slotcrafter.Slotcrafter
api-version: '1.20'
commands:
  setslots:
    description: Sets the slot limit.
    usage: /<command> <new limit/auto>