name: slotcrafter
version: '${project.version}'
main: org.asdanjer.slotcrafter.Slotcrafter
depend:
  - spark
softdepend:
  - SuperVanish
  - PremiumVanish
  - PlaceholderAPI
api-version: '1.20'
commands:
  setslots:
    description: Sets the slot limit.
    usage: /<command> <new limit/auto>
    permission: slotcrafter.setslotlimit
    tab-completion: true
  slotcrafter:
    description: Updates the config setting.
    usage: /<command> update <config setting> <value> or /slotcrafter info
    permission: slotcrafter.admin
    permission-message: You do not have permission to use this command.
    tab-completion: true
  yeetme:
    description: Toggle automatic kick when MSPT gets too high.
    usage: /<command> or /<command> <mspt>
    permission: slotcrafter.yeetme
  yeetthem:
    description: Kick all players who have enabled automatic kick.
    usage: /<command>
    permission: slotcrafter.yeetthem
  takemyslot:
    description: Allows players to offer their slot for a specified time.
    usage: /<command> <time in hours>
    permission: slotcrafter.takemyslot
permissions:
  slotcrafter.setslotlimit:
    description: Allows access to the SlotLimitCommand.
    default: op
  slotcrafter.admin:
    description: Allows access to changing config values and get info
    default: op
  slotcrafter.yeetme:
    description: Allows people to opt into yeeting.
    default: true
  slotcrafter.yeetthem:
    description: Allows people to kick opt in players.
    default: op
  slotcrafter.ignorecap:
    description: Allows people to ignore the slot cap.
    default: op
  slotcrafter.takemyslot:
    description: Allows people to offer their slot.
    default: true